name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry==2.1.4

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Black
        run: poetry run black --check src tests

      - name: Run Mypy
        run: poetry run mypy src tests

      - name: Run Pytest
        run: poetry run pytest --cov
